### ISSUE TITLE
ZynReverb plugin crashes when room size set to 127

### ISSUE THREAD

**Issue by ctsexton** [zynaddsubfx/zyn-fusion-issues#193]
This only seems to occur when ZynReverb is loaded as a plugin on its own. If I use carla or ardour to load ZynReverb and turn "Room Size" above 125 (i.e. 126 or 127), carla and ardour both crash immediately.

**Comment by ctsexton** [comment]
Actually it also happens (not always) in zynaddsubfx as well. Zynaddsubfx process crashes, zyn-fusion gui stays alive and displays: "CONNECTION TO REMOTE ZYN LOST". 

And in the terminal: 
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Comment by pdesaulniers** [comment]
Valgrind output:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
==11670== 
==11670== Process terminating with default action of signal 6 (SIGABRT): dumping core
==11670==    at 0x5C38D7F: raise (in /usr/lib/libc-2.28.so)
==11670==    by 0x5C23671: abort (in /usr/lib/libc-2.28.so)
==11670==    by 0x612458D: __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] (vterminate.cc:95)
==11670==    by 0x612ADF9: __cxxabiv1::__terminate(void (*)()) (eh_terminate.cc:47)
==11670==    by 0x612AE56: std::terminate() (eh_terminate.cc:57)
==11670==    by 0x612B0AB: __cxa_throw (eh_throw.cc:95)
==11670==    by 0xFCA61A5: float* zyn::Allocator::valloc<float>(unsigned long) (Allocator.h:66)
==11670==    by 0xFCA2831: zyn::Reverb::settype(unsigned char) (Reverb.cpp:379)
==11670==    by 0xFCA2CF5: zyn::Reverb::setroomsize(unsigned char) (Reverb.cpp:425)
==11670==    by 0xFCA3343: zyn::Reverb::changepar(int, unsigned char) (Reverb.cpp:516)
==11670==    by 0xFC9F5E8: AbstractPluginFX<zyn::Reverb>::setParameterValue(unsigned int, float) (AbstractFX.hpp:138)
==11670==    by 0xFC9D441: DISTRHO::PluginExporter::setParameterValue(unsigned int, float) (DistrhoPluginInternal.hpp:346)
```

**Comment by fundamental** [comment]
That sounds like the memory pool running out of space. As such I cannot replicate on the standalone (it seems to handle that case correctly there), but it does look like replicating the issue in the plugin version isn't that hard.

**Comment by pdesaulniers** [comment]
GDB bt full, in case this is useful:
```
#0  0x00007ffff6a84d7f in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6a6f672 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff667158e in __gnu_cxx::__verbose_terminate_handler() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
        terminating = true
        t = <optimized out>
#3  0x00007ffff6677dfa in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff6677e57 in std::terminate() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff66780ac in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*)) (obj=<optimized out>, tinfo=0x7ffff6768d10 <typeinfo for std::bad_alloc>, dest=0x7ffff66761e0 <std::bad_alloc::~bad_alloc()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
        globals = <optimized out>
        header = 0x7fffd0000b20
#6  0x00007ffff38c11a6 in zyn::Allocator::valloc<float>(unsigned long) (this=0x5555559bca48, len=150496) at /tmp/zynaddsubfx/src/Effects/../Misc/Allocator.h:66
        data = 0x0
#7  0x00007ffff38bd832 in zyn::Reverb::settype(unsigned char) (this=0x555555985d50, _Ptype=1 '\001') at /tmp/zynaddsubfx/src/Effects/Reverb.cpp:379
        i = 15
        NUM_TYPES = 3
        combtunings = {{0, 0, 0, 0, 0, 0, 0, 0}, {1116, 1188, 1277, 1356, 1422, 1491, 1557, 1617}, {1116, 1188, 1277, 1356, 1422, 1491, 1557, 1617}}
        aptunings = {{0, 0, 0, 0}, {225, 341, 441, 556}, {225, 341, 441, 556}}
        samplerate_adjust = 1
        tmp = 150496.5
#8  0x00007ffff38bdcf6 in zyn::Reverb::setroomsize(unsigned char) (this=0x555555985d50, _Proomsize=127 '\177') at /tmp/zynaddsubfx/src/Effects/Reverb.cpp:425
#9  0x00007ffff38be344 in zyn::Reverb::changepar(int, unsigned char) (this=0x555555985d50, npar=11, value=127 '\177') at /tmp/zynaddsubfx/src/Effects/Reverb.cpp:516
#10 0x00007ffff38ba5e9 in AbstractPluginFX<zyn::Reverb>::setParameterValue(unsigned int, float) (this=0x5555559bca00, index=9, value=127) at /tmp/zynaddsubfx/src/Plugin/Reverb/../AbstractFX.hpp:138
        ivalue = 127
#11 0x00007ffff38b8442 in DISTRHO::PluginExporter::setParameterValue(unsigned int, float) (this=0x5555555a18f0, index=9, value=127) at /tmp/zynaddsubfx/DPF/distrho/src/DistrhoPluginInternal.hpp:346
#12 0x00007ffff38b8e26 in DISTRHO::PluginLv2::lv2_run(unsigned int) (this=0x5555555a18f0, sampleCount=512) at /tmp/zynaddsubfx/DPF/distrho/src/DistrhoPluginLV2.cpp:515
        i = 9
        count = 11
        curValue = 127
#13 0x00007ffff38b4416 in DISTRHO::lv2_run(LV2_Handle, uint32_t) (instance=0x5555555a18f0, sampleCount=512) at /tmp/zynaddsubfx/DPF/distrho/src/DistrhoPluginLV2.cpp:1087
#14 0x000055555555bc8c in  ()
#15 0x000055555555fd74 in  ()
#16 0x00007ffff7d31d8e in  () at /usr/lib/libjack.so.0
#17 0x00007ffff7d31c96 in  () at /usr/lib/libjack.so.0
#18 0x00007ffff7d2f4db in  () at /usr/lib/libjack.so.0
#19 0x00007ffff7d50072 in  () at /usr/lib/libjack.so.0
#20 0x00007ffff7f61a9d in start_thread () at /usr/lib/libpthread.so.0
#21 0x00007ffff6b48b23 in clone () at /usr/lib/libc.so.6
```

**Comment by pdesaulniers** [comment]
@fundamental What would be a way of fixing this? Could we reserve more space somehow?

**Comment by fundamental** [comment]
On 12-27, Patrick Desaulniers wrote:
> @fundamental What would be a way of fixing this? Could we reserve more space somehow?
First and foremost fixing the out-of-memory crash should be an
easy/simple fix.
What to use as a retry mechanism will be more complex.
e.g. it could be a reverb flag which will try to reallocate the buffer
if it knows that it was previously out of memory at the start of each
audio frame.


Reserving more space is only a partial solution for the full synth
situation as out-of-memory is not that difficult to create with the RT
memory pool.

Per the original topic of the Reverb plugin (as it's own) crashing, then
that has a known ahead of time absolute memory usage, so it might make
sense to use that size there (if it isn't excessively large).
Some of the parameter ranges in zyn are a bit overly generous beyond
what's helpful in sound design IMO.
