### ISSUE TITLE
Alpine - Sementation fault on zest_open()

### ISSUE THREAD

**Issue by UniqueActive** [zynaddsubfx/zyn-fusion-issues#380]
Hello,

I have been trying to build zyn-fusion for Alpine Linux since I can't afford buying it currently, but I have trouble running it, it segfaults during zest_open(). I figured that it's an issue of the GUI since zynaddsubfx starts just fine without GUI, so I tried to debug zest, however I am not really getting a useful backtrace of the segfault:

```
~/src/zyn-fusion-build/src/mruby-zest-build $ make gdb
gdb --args ./zest osc.udp://127.0.0.1:1337
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./zest...
(gdb) run
Starting program: /home/unicorn/src/zyn-fusion-build/src/mruby-zest-build/zest osc.udp://127.0.0.1:1337
[INFO] Succeeded in loading development libzest.so
z.zest_open = 0
z.zest_setup = 0
z.zest_close = 0
z.zest_draw = 0
z.zest_tick = 0
z.zest_motion = 0
z.zest_scroll = 0
z.zest_mouse = 0
z.zest_key = 0
z.zest_special = 0
z.zest_resize = 0
z.zest_exit = 0
z.zest_set_option = 0
z.zest_dnd_drop = 0
z.zest_dnd_pick = 0
z.zest_script = 0
z.zest_get_remote_url = 0
[INFO:Zyn] setup_pugl()
[New LWP 20642]
[INFO:Zyn] zest_tick()
[INFO:Zyn] zest_open()

Thread 1 "zest" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005555555569f2 in onDisplay ()
#2  0x0000555555556cd1 in onEvent ()
#3  0x0000555555559054 in puglDispatchEvent ()
#4  0x000055555555cfd1 in puglProcessEvents ()
#5  0x0000555555558425 in main ()
(gdb) 
```

If you have any clues what I may be missing (runtime dependencies?) or how I can get more verbose debug output, please let me know, I would appreciate it a lot!

**Comment by UniqueActive** [comment]
Update based on conversation with @fundamental on IRC:

The issue is due to improper linking of libzest.so, because the makefile of the GUI contains some non-portable code. Specifically, this change breaks portability of the script for musl find, since it uses GNU features: https://github.com/mruby-zest/mruby-zest-build/commit/d074b4165d43bd9f32e2d6a50a924d6c73d76a73

Once this is undone and merged, the issue will be resolved.

**Comment by fundamental** [comment]
Fixed
